#define LOCATION_HOME_OFFSET 0

#define LOCATION_INDENT_0 1
#define LOCATION_INDENT_1 2
#define LOCATION_INDENT_2 3
#define LOCATION_INDENT_3 4
#define LOCATION_INDENT_4 5
#define LOCATION_INDENT_5 6
#define LOCATION_INDENT_6 7
#define LOCATION_INDENT_7 8 
#define LOCATION_INDENT_8 9 
#define LOCATION_INDENT_9 10
#define LOCATION_INDENT_10 11
#define LOCATION_INDENT_11 12



