#define LOCATION_HOME_OFFSET 0

#define LOCATION_TEST_INDENT_0 1
#define LOCATION_TEST_INDENT_1 2
#define LOCATION_TEST_INDENT_2 3
#define LOCATION_TEST_INDENT_3 4
#define LOCATION_TEST_INDENT_4 5
#define LOCATION_TEST_INDENT_5 6
#define LOCATION_TEST_INDENT_6 7
#define LOCATION_TEST_INDENT_7 8 
#define LOCATION_TEST_INDENT_8 9 
#define LOCATION_TEST_INDENT_9 10
#define LOCATION_TEST_INDENT_10 11
#define LOCATION_TEST_INDENT_11 12

//Encoder values of each of the indents
#define LOCATION_INDENT_DIAL_0 13 //Int storage
#define LOCATION_INDENT_DIAL_1 15
#define LOCATION_INDENT_DIAL_2 17
#define LOCATION_INDENT_DIAL_3 19
#define LOCATION_INDENT_DIAL_4 21
#define LOCATION_INDENT_DIAL_5 23
#define LOCATION_INDENT_DIAL_6 25
#define LOCATION_INDENT_DIAL_7 27
#define LOCATION_INDENT_DIAL_8 29
#define LOCATION_INDENT_DIAL_9 31
#define LOCATION_INDENT_DIAL_10 33
#define LOCATION_INDENT_DIAL_11 35

#define LOCATION_SERVO_REST 37 //Ints
#define LOCATION_SERVO_TEST_PRESSURE 39
#define LOCATION_SERVO_HIGH_PRESSURE 41


